sudo: true

dist: trusty

language: cpp

compiler: gcc

install:
  - ~/build/HaliteChallenge/Halite/halite/visualizer/debianInstall.sh
  - export CXX="g++-4.8"

script:
  - ls /usr/include
  - ls /usr/local/include

  - cd ~/build/HaliteChallenge/Halite/halite/environment
  - make

  - cd ../visualizer
  - make

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
