sudo: true

dist: trusty

language: cpp

compiler: gcc

install:
  - ~/build/HaliteChallenge/Halite/halite/visualizer/debianInstall.sh
  - sudo apt-get install -y python3 openjdk-7-jdk
  - export CXX="g++-4.8"

script:
  - cd ~/build/HaliteChallenge/Halite/airesources/Java
  - javac MyBot.java
  - javac BasicBot.java

  - cd ../C++
  - g++ -std=c++11 MyBot.cpp -o MyBot.o
  - g++ -std=c++11 BasicBot.cpp -o BasicBot.o

  - cd ~/build/HaliteChallenge/Halite/halite/environment
  - make
  - ./environment 10 10 "python3 ../../airesources/Python/MyBot.py" "cd ../../airesources/Java; java MyBot" "../../airesources/C++/MyBot.o"

  - ./environment 10 10 "python3 ../../airesources/Python/BasicBot.py" "cd ../../airesources/Java; java BasicBot" "../../airesources/C++/BasicBot.o"

  - cd  ~/build/HaliteChallenge/Halite/halite/visualizer
  - make

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
