language: cpp

compiler: gcc

install:
  - halite/visualizer/debianInstall.sh
  - export CXX="g++-4.8"

script:
  - cd halite/environment
  - make
  - cd ../visualizer
  - make

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
