sudo: true

dist: trusty

language: cpp

compiler: gcc

install:
  - cd halite/visualizer
  - sudo apt-get install -y g++-4.8 libstdc++6-4.7-dev
  - sudo apt-get install -y libXmu-dev libXi-dev dos2unix git wget
  - sudo apt-get install -y libfreetype6-dev libglew-dev pkg-config
  - echo "Done with non glfw3"
  
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get upgrade -y
  - sudo apt-get install -y xorg-dev libglu1-mesa-dev
  - sudo apt-get build-dep -y glfw3
  - sudo apt-get build-dep -y glfw
  - echo "Done with glfw3 setup"
  
  - sudo apt-get install -y unzip wget
  - yes | wget https://github.com/glfw/glfw/releases/download/3.2/glfw-3.2.zip
  - yes | unzip glfw-3.2.zip -d glfw
  - cd glfw/glfw-3.2
  - cmake -G "Unix Makefiles"
  - "Ready to build glfw3"
  
  - sudo make
  - sudo make install
  - export CXX="g++-4.8"

script:
  - cd halite/environment
  - make
  - cd ../visualizer
  - make

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
